In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout


In [3]:
df = pd.read_csv("hospitalreadmission.csv")
df

,age,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,gender_Male,diabetes_med_Yes,insulin_No,insulin_Steady,insulin_Up,readmitted
0,24,3,41,0,3,1,0,2,3,1,1,1,0,0,1
1,73,1,26,3,57,1,1,0,12,1,0,1,0,0,1
2,65,9,62,3,17,1,1,0,1,0,1,0,1,0,1
3,49,10,79,5,57,3,0,3,8,0,1,1,0,0,1
4,49,11,32,4,45,0,2,1,9,0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,33,7,60,1,31,1,1,3,13,1,1,0,0,1,1
4996,71,14,65,1,78,1,1,1,13,1,1,0,1,0,1
4997,77,5,79,2,19,2,2,0,12,0,1,0,1,0,0
4998,66,8,56,2,46,2,2,1,1,1,1,0,0,1,0


In [4]:
df.shape

(5000, 15)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   age                 5000 non-null   int64
 1   time_in_hospital    5000 non-null   int64
 2   num_lab_procedures  5000 non-null   int64
 3   num_procedures      5000 non-null   int64
 4   num_medications     5000 non-null   int64
 5   number_outpatient   5000 non-null   int64
 6   number_emergency    5000 non-null   int64
 7   number_inpatient    5000 non-null   int64
 8   number_diagnoses    5000 non-null   int64
 9   gender_Male         5000 non-null   int64
 10  diabetes_med_Yes    5000 non-null   int64
 11  insulin_No          5000 non-null   int64
 12  insulin_Steady      5000 non-null   int64
 13  insulin_Up          5000 non-null   int64
 14  readmitted          5000 non-null   int64
dtypes: int64(15)
memory usage: 586.1 KB


In [6]:
df.isnull().sum()

age                   0
time_in_hospital      0
num_lab_procedures    0
num_procedures        0
num_medications       0
number_outpatient     0
number_emergency      0
number_inpatient      0
number_diagnoses      0
gender_Male           0
diabetes_med_Yes      0
insulin_No            0
insulin_Steady        0
insulin_Up            0
readmitted            0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [9]:
X = df.drop('readmitted', axis=1)
y = df['readmitted']
            

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42, stratify=y)

In [12]:
s = StandardScaler()
X_train = s.fit_transform(X_train)
X_test = s.fit_transform(X_test)
# X_train

array([[ 0.39910052,  0.6520971 ,  0.59435202, ..., -0.92994724,
        -0.63871351,  2.42096333],
       [ 1.59429854,  1.65648231, -1.12798437, ...,  1.07532982,
        -0.63871351, -0.41305871],
       [ 0.63814013,  0.6520971 ,  1.67446128, ..., -0.92994724,
         1.56564718, -0.41305871],
       ...,
       [ 0.68594805,  0.6520971 , -0.69010224, ...,  1.07532982,
        -0.63871351, -0.41305871],
       [-0.22240245,  1.405386  , -0.77767867, ..., -0.92994724,
        -0.63871351,  2.42096333],
       [ 0.73375597,  1.65648231, -0.36898868, ..., -0.92994724,
         1.56564718, -0.41305871]], shape=(4000, 14))

In [13]:
#X_test

array([[-0.1185083 ,  0.38080305, -1.09464699, ..., -0.89362249,
        -0.65777257,  2.36197954],
       [-0.02089026, -1.12137862,  1.61769069, ...,  1.11904077,
        -0.65777257, -0.42337369],
       [ 0.8576721 , -0.37028778,  0.24693939, ...,  1.11904077,
        -0.65777257, -0.42337369],
       ...,
       [ 1.1017172 ,  0.38080305, -1.67794541, ...,  1.11904077,
        -0.65777257, -0.42337369],
       [-1.38754282,  0.63116667,  0.1302797 , ..., -0.89362249,
        -0.65777257, -0.42337369],
       [-1.04587968, -1.12137862, -0.80299778, ...,  1.11904077,
        -0.65777257, -0.42337369]], shape=(1000, 14))

In [19]:
# Build ANN layer 
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))


In [20]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)


In [21]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                      │ (None, 64)                  │             960 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_3 (Dropout)                  │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,585 (14.00 KB)

 Trainable params: 3,585 (14.00 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
# train_mode
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.20,
    verbose=1
)

Epoch 1/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6975 - loss: 0.5768 - val_accuracy: 0.7375 - val_loss: 0.5022
Epoch 2/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7581 - loss: 0.5029 - val_accuracy: 0.7625 - val_loss: 0.4894
Epoch 3/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7634 - loss: 0.4986 - val_accuracy: 0.7625 - val_loss: 0.4828
Epoch 4/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7753 - loss: 0.4887 - val_accuracy: 0.7625 - val_loss: 0.4809
Epoch 5/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7713 - loss: 0.4860 - val_accuracy: 0.7613 - val_loss: 0.4824
Epoch 6/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7731 - loss: 0.4883 - val_accuracy: 0.7650 - val_loss: 0.4826
Epoch 7/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7784 - loss: 0.4769 - val_accuracy: 0.7650 - val_loss: 0.4809
Epoch 8/100
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7756 - loss: 0.4752 - val_accu

In [25]:
# probba
y_pred_probab = model.predict(X_test)
y_pred_probab 

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


array([[0.5646241 ],
       [0.82742   ],
       [0.686039  ],
       [0.99842477],
       [0.8460619 ],
       [0.8308852 ],
       [0.7808673 ],
       [0.85950214],
       [0.86726326],
       [0.950135  ],
       [0.9268403 ],
       [0.19075869],
       [0.6508176 ],
       [0.08821313],
       [0.9419686 ],
       [0.29086784],
       [0.9945872 ],
       [0.8694575 ],
       [0.45681334],
       [0.5873367 ],
       [0.82768214],
       [0.96784943],
       [0.9383856 ],
       [0.8800399 ],
       [0.52255386],
       [0.79735154],
       [0.63934636],
       [0.6018702 ],
       [0.71738267],
       [0.81481034],
       [0.9936119 ],
       [0.91544056],
       [0.62056315],
       [0.60217273],
       [0.99637264],
       [0.99384993],
       [0.86102366],
       [0.9444486 ],
       [0.8154797 ],
       [0.5257887 ],
       [0.9733955 ],
       [0.86248976],
       [0.7457391 ],
       [0.86288744],
       [0.5922358 ],
       [0.68409616],
       [0.94538325],
       [0.368

In [24]:
y_pred = (y_pred_probab >= 0.5).astype(int)
# y_pred

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [26]:
print('accuracy', accuracy_score(y_test, y_pred))

accuracy 0.75


In [27]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.51      0.35      0.42       255
           1       0.80      0.89      0.84       745

    accuracy                           0.75      1000
   macro avg       0.66      0.62      0.63      1000
weighted avg       0.73      0.75      0.73      1000



In [28]:
new_patient = pd.DataFrame({
    "age":[70],
    "gender":["Male"],
    "admission_type":["Emergency"],
    "diagnosis":["Diabetes"],
    "num_lab_procedures" :[55],
    "num_medictions": [15],
    "time_in_hospital": [6],
    "previous_visits":[3]
})

In [29]:
new_patient = pd.get_dummies(new_patient,
                             drop_first=True
                            )

In [30]:
new_patient = new_patient.reindex(
    columns=X.columns,
    fill_value=0
)

In [31]:
new_patient_scaled = s.transform(new_patient)
new_patient_scaled

array([[ 0.8576721 , -0.37028778, -0.13220459, -1.46559628, -1.79161629,
        -1.19748308, -0.84878154, -0.92484214, -1.90042278, -1.02634696,
        -1.76021608, -0.89362249, -0.65777257, -0.42337369]])

In [32]:
probability = model.predict(new_patient_scaled)[0][0]
print("Readmission Probability:", probability)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
Readmission Probability: 0.30234846
