In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = tf.constant(5)
x

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [6]:
x = tf.constant([1.5,3.4,4.7])
print(x)

tf.Tensor([1.5 3.4 4.7], shape=(3,), dtype=float32)


In [7]:
x = tf.constant([1,2,3,4])
x

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [9]:
m = tf.constant([[
    [1,2],
    [3,4]
]])
m

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [10]:
m.shape

TensorShape([1, 2, 2])

In [12]:
a = np.array([1,2,3])

t = tf.constant(a)

print(t)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [13]:
a = tf.constant(10)
b = tf.constant(20)
c =  a + b
print(type(c))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [14]:
print(tf.multiply(a,b))

tf.Tensor(200, shape=(), dtype=int32)
