In [1]:
# Z Score = (Xi- meu)/Sigma
#  where xi = individual age, salary value
#  meu = mean of age , salary
# sigma = standard deviation
# (z - scorescaling)
# two type
# standardlization z-score
# normalization min,max 
#after scaling brings mean to zero(0) and std dev to one(1)


In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Social_Network_Ads.csv")
df.head()# display first five row
                 

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0


In [13]:
# df = df.iloc [:,2:0]#iloc means select rows and 
# columns by their numerical position.
# # df.iloc[rows, columns(first no say start from that coulmn no and second number say just stop before this column]


# df

""
0
1
2
3
4
...
395
396
397
398


In [26]:
X = df.drop('Purchased', axis=1)
X#Remove the Purchased column from df and put everything else into X.

y = df['Purchased']
y #Take the Purchased column from df and put it into y.
            

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [33]:
X = df.drop("Gender", axis=1)
X


,User ID,Age,EstimatedSalary,Purchased
0,15624510,19,19000,0
1,15810944,35,20000,0
2,15668575,26,43000,0
3,15603246,27,57000,0
4,15804002,19,76000,0
...,...,...,...,...
395,15691863,46,41000,1
396,15706071,51,23000,1
397,15654296,50,20000,1
398,15755018,36,33000,0


In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y, test_size=0.2,random_state=1)

In [36]:
X_train

,User ID,Age,EstimatedSalary,Purchased
93,15699284,29,28000,0
23,15599081,45,22000,1
299,15747043,46,117000,1
13,15704987,32,18000,0
90,15684801,22,81000,0
...,...,...,...,...
255,15750056,52,90000,1
72,15595228,20,23000,0
396,15706071,51,23000,1
235,15646227,46,79000,1


In [37]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)#learns how to scale it

StandardScaler()

In [38]:
X_train_scaled = scaler.transform(X_train)
X_train_scaled


array([[ 0.06699777, -0.80330081, -1.19121795, -0.72876641],
       [-1.32816737,  0.75697997, -1.36859801,  1.3721818 ],
       [ 0.73196481,  0.85449752,  1.43991958,  1.3721818 ],
       ...,
       [ 0.1614958 ,  1.34208527, -1.33903467,  1.3721818 ],
       [-0.67173537,  0.85449752,  0.31651254,  1.3721818 ],
       [-0.0702729 , -0.70578326, -0.57038775, -0.72876641]],
      shape=(320, 4))

In [18]:
#normalization is feature scaling technique which  brings value in range of 0 and 1

In [41]:
# normalization :
from sklearn.preprocessing import MinMaxScaler#MinMaxScaler checks the value's position between MIN and MAX and converts that position to 0–1. ✅
mms = MinMaxScaler()
mmscaled = mms.fit(X_train)
mms_x_train_scaled = mms.transform(X_train)
mms_x_train_scaled

array([[0.53348059, 0.26190476, 0.0962963 , 0.        ],
       [0.13032545, 0.64285714, 0.05185185, 1.        ],
       [0.72563338, 0.66666667, 0.75555556, 1.        ],
       ...,
       [0.5607873 , 0.78571429, 0.05925926, 1.        ],
       [0.32001191, 0.66666667, 0.47407407, 1.        ],
       [0.49381405, 0.28571429, 0.25185185, 0.        ]], shape=(320, 4))

In [42]:

mms = MinMaxScaler()
mmscaled = mms.fit(X_test)
mms_x_test_scaled = mms.transform(X_test)
mms_x_test_scaled

array([[0.77181887, 0.42857143, 0.13953488, 0.        ],
       [0.53034366, 0.5       , 0.35658915, 0.        ],
       [0.9439092 , 0.42857143, 0.79844961, 1.        ],
       [0.40019235, 0.5       , 0.82945736, 1.        ],
       [0.93687287, 0.19047619, 0.79844961, 0.        ],
       [0.61586214, 0.47619048, 0.3875969 , 0.        ],
       [0.46049246, 0.04761905, 0.1627907 , 0.        ],
       [0.11191929, 0.73809524, 0.57364341, 1.        ],
       [0.41641339, 0.30952381, 0.02325581, 0.        ],
       [0.28730296, 0.71428571, 0.97674419, 0.        ],
       [0.31082679, 0.38095238, 0.44186047, 0.        ],
       [0.25082646, 0.5       , 0.4496124 , 0.        ],
       [0.43535735, 0.4047619 , 0.44186047, 0.        ],
       [0.02334063, 0.71428571, 0.89922481, 1.        ],
       [0.17299381, 0.83333333, 0.51937984, 1.        ],
       [0.48173885, 0.9047619 , 0.91472868, 1.        ],
       [0.85394826, 1.        , 0.52713178, 1.        ],
       [0.66254757, 0.21428571,